#!/bin/bash

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

while true; do
    clear
    echo -e "${YELLOW}=========================${NC}"
    echo -e "${GREEN}      OS Menu By Para     ${NC}"
    echo -e "${YELLOW}=========================${NC}"
    echo -e "${CYAN}1) Install Ubuntu 22${NC}"
    echo -e "${CYAN}2) Install Debian 12${NC}"
    echo -e "${CYAN}3) Install CentOs-Steam-9${NC}"
    echo -e "${CYAN}4) Exit${NC}"
    echo -e "${YELLOW}=========================${NC}"
    echo -e -n "${YELLOW}Enter your choice [1-3]: ${NC}"
    read choice

    case $choice in
        1)
            echo -e "${GREEN}Running Ubuntu 22 install script...${NC}"
            bash <(curl -s https://raw.githubusercontent.com/ParaNoob123/Blueprint/refs/heads/main/ubuntu22)
            read -p "Press enter to return to menu..."
            ;;
        2)
            echo -e "${GREEN}Running Debian 12 install script...${NC}"
            bash <(curl -s https://raw.githubusercontent.com/ParaNoob123/Blueprint/refs/heads/main/debain12)
            read -p "Press enter to return to menu..."
            ;;
        3)
            echo -e "${GREEN}Running Debian 12 install script...${NC}"
            bash <(curl -s https://raw.githubusercontent.com/ParaNoob123/Blueprint/refs/heads/main/CentOs9Install)
            read -p "Press enter to return to menu..."
            ;;
        4)
            echo -e "${GREEN}Goodbye!${NC}"
            exit 0
            ;;
        *)
            echo -e "${YELLOW}Invalid option, try again.${NC}"
            sleep 1
            ;;
    esac
done
