#!/bin/bash

# Para ASCII Art and Header
echo -e "\n\033[1;36m"
cat << "EOF"

  
  _____        _____            
 |  __ \ /\   |  __ \     /\    
 | |__) /  \  | |__) |   /  \   
 |  ___/ /\ \ |  _  /   / /\ \  
 | |  / ____ \| | \ \  / ____ \ 
 |_| /_/    \_\_|  \_\/_/    \_\
                                
                                

 🤍 Framework Installer - github.com/ParaNoob123

EOF
echo -e "\033[0m"

echo -e "\033[1;34mStarting Installation of Blueprint.zip\033[0m"
echo "-------------------------------------"

# Installation Steps
commands=(
  "apt update -y"
  "curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
sudo apt update
sudo apt install playit"
  "sudo systemctl start playit"
  "sudo systemctl enable playit"
  "playit setup"
)

# Execute commands with progress
for i in "${!commands[@]}"; do
  echo -e "\033[1;33m[$((i+1))/14] Executing:\033[0m \033[0;35m${commands[$i]}\033[0m"
  eval "${commands[$i]}"
  if [ $? -ne 0 ]; then
    echo -e "\033[1;31mError occurred at step $((i+1)). Aborting installation.\033[0m"
    exit 1
  fi
done

# Completion Message
echo -e "\n\033[1;32m-------------------------------------\033[0m"
echo -e "\033[1;32mBlueprint extensions installed successfully! 🎉\033[0m"
echo -e "\033[1;35m           Made by Para\033[0m"
echo -e "\033[1;35m       github.com/Para\033[0m"
echo -e "\033[1;32m-------------------------------------\033[0m"
