#!/bin/bash

# Para ASCII Art and Header
echo -e "\n\033[1;36m"
cat << "EOF"

  
  _____        _____            
 |  __ \ /\   |  __ \     /\    
 | |__) /  \  | |__) |   /  \   
 |  ___/ /\ \ |  _  /   / /\ \  
 | |  / ____ \| | \ \  / ____ \ 
 |_| /_/    \_\_|  \_\/_/    \_\
                                
                                

 🤍 Playit Tunneling - github.com/ParaNoob123

EOF
echo -e "\033[0m"

echo -e "\033[1;34mStarting Installation of Playit Tunneling\033[0m"
echo "-------------------------------------"

# Installation Steps
commands=(
  "sudo apt update"
  "wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
chmod +x playit-linux-amd64
./playit-linux-amd64"
)

# Execute commands with progress
for i in "${!commands[@]}"; do
  echo -e "\033[1;33m[$((i+1))/14] Executing:\033[0m \033[0;35m${commands[$i]}\033[0m"
  eval "${commands[$i]}"
  if [ $? -ne 0 ]; then
    echo -e "\033[1;31mError occurred at step $((i+1)). Aborting installation.\033[0m"
    exit 1
  fi
done

# Completion Message
echo -e "\n\033[1;32m-------------------------------------\033[0m"
echo -e "\033[1;32m Playit Tunneling Done 🎉\033[0m"
echo -e "\033[1;35m           Made by Para\033[0m"
echo -e "\033[1;35m       github.com/Para\033[0m"
echo -e "\033[1;32m-------------------------------------\033[0m"
