#!/bin/bash

# Para ASCII Art and Header
echo -e "\n\033[1;36m"
cat << "EOF"

  
  _____        _____            
 |  __ \ /\   |  __ \     /\    
 | |__) /  \  | |__) |   /  \   
 |  ___/ /\ \ |  _  /   / /\ \  
 | |  / ____ \| | \ \  / ____ \ 
 |_| /_/    \_\_|  \_\/_/    \_\
                                
                                

 🤍 Skyport Panel Installer - github.com/ParaNoob123

EOF
echo -e "\033[0m"

echo -e "\033[1;34mStarting Installation of Skyport\033[0m"
echo "-------------------------------------"

# Installation Steps
commands=(
  "curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -"
  "apt-get install nodejs -y"
  "apt install docker.io -y"
  "sudo apt install git -y"
  "mkdir -p panel5"
  "cd panel5"
  "git clone https://github.com/achul123/panel5.git"
  "cd panel5"
  "npm install"
  "npm run seed"
  "npm run createUser"
  "sudo npm install -g pm2"
  "pm2 start index.js"
)

# Execute commands with progress
for i in "${!commands[@]}"; do
  echo -e "\033[1;33m[$((i+1))/14] Executing:\033[0m \033[0;35m${commands[$i]}\033[0m"
  eval "${commands[$i]}"
  if [ $? -ne 0 ]; then
    echo -e "\033[1;31mError occurred at step $((i+1)). Aborting installation.\033[0m"
    exit 1
  fi
done

# Completion Message
echo -e "\n\033[1;32m-------------------------------------\033[0m"
echo -e "\033[1;34m Your Panel Can Be Accesabile From localhost:3001\033[0m"
echo -e "\033[1;32m Skyport installed successfully! 🎉\033[0m"
echo -e "\033[1;35m           Made by Para\033[0m"
echo -e "\033[1;35m       github.com/Para\033[0m"
echo -e "\033[1;32m-------------------------------------\033[0m"
